Smadot.Web/Models/Equipo/EquipoViewModel.cs
using Smadot.Models.Entities.Equipo.Response;
using Smadot.Models.DataBase;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Smadot.Models.Entities.Linea.Response;

namespace Smadot.Web.Models.Equipo
{
    public class EquipoViewModel
    {
        public long Id { get; set; }

        public string? Nombre { get; set; } 

        public string? NumeroSerie { get; set; } 

        public int IdCatEstatusEquipo { get; set; }

        public long IdUserRegistro { get; set; }

        public DateTime FechaRegistro { get; set; }

        public long? IdUserReviso { get; set; }

        public string? Comentarios { get; set; }

        public long? IdLinea { get; set; }

        public long IdVerificentro { get; set; }

        public string? FilesString { get; set; }

        public List<EquipoFiles> Files { get; set; }

        public List<SelectListItem> Lineas { get; set; }
    }

    public class EquipoFiles
    {
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Base64 { get; set; }
    }

    public class AuxValidarResponse
    {
        public long Id { get; set; }
    }
}

Smadot.Web/Controllers/AdministracionStock/EquipoController.cs
using Microsoft.AspNetCore.Mvc;
using Smadot.Models.Entities.Equipo.Request;
using Smadot.Models.Entities.Equipo.Response;
using Smadot.Models.Entities.Linea.Request;
using Smadot.Models.Entities.Linea.Response;
using Smadot.Utilities.ProxyWebAPI.Interfaces;
using Smadot.Web.Helper.Operaciones.AdministracionStock;
using Smadot.Web.Helper.Operaciones.Catalogo;
using Microsoft.AspNetCore.Mvc.Rendering;
using Smadot.Utilities.Modelos;
using Smadot.Models.Entities.Generic.Response;
using Smadot.Web.Utilities;
using Smadot.Web.Models;
using System;
using Newtonsoft.Json;
using Smadot.Web.Handler.Autorizacion;
using Smadot.Utilities.GestionTokens;
using Smadot.Utilities.Reporting.Interfaces;
using Smadot.Models.Entities.SolicitudFormaValorada.Request;
using Smadot.Web.Models.Exento;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Smadot.Models.Entities.Catalogos.Response;
using Smadot.Utilities.BlobStorage;
using Smadot.Utilities.FileStorage;
using Smadot.Models.Dicts;
using System.ComponentModel.DataAnnotations;
using Smadot.Models.DataBase;
using System.Net;
using Smadot.Models.Entities.Catalogos.Request;

namespace Smadot.Web.Controllers.AdministracionStock
{
    [Authorize]
    public class EquipoController : Controller
    {
        private readonly IProxyWebAPI _proxyWebAPI;
        private readonly IUserResolver _userResolver;
        private readonly BlobStorage _blobStorage;


        //Mensaje genérico de error
        public string _mensajeErrorCatch = "Ocurrió un error al realizar la operación";

        public EquipoController(IProxyWebAPI proxyWebAPI, IUserResolver userResolver, IConfiguration configuration)
        {
            _proxyWebAPI = proxyWebAPI;
            _userResolver = userResolver;
            _blobStorage = new BlobStorage(configuration["ConnectionBlobStrings:BlobString"], configuration["ConnectionBlobStrings:Container"]);
        }

        public IActionResult Index()
        {
            if (!_userResolver.HasPermission(MenuInventarioEquipos.PermisoMenuPadre))
                return new UnauthorizedResult();
            return View("~/Views/Equipo/Index.cshtml");
        }

        [HttpPost]
        public async Task<JsonResult> Consulta()
        {
            JsonResult result = new JsonResult("");

            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");

            var request = new EquipoRequest();
            request.Pagina = skip / pageSize + 1;
            request.Registros = pageSize;
            request.Busqueda = Request.Form["search[value]"].FirstOrDefault();
            request.ColumnaOrdenamiento = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            request.Ordenamiento = Request.Form["order[0][dir]"].FirstOrDefault();

            var listaResult = await EquipoHelper.Consulta(_proxyWebAPI, request);
            var data = listaResult.Result as List<vEquipoResponse> ?? new List<vEquipoResponse>();

            ////Almacena el total de registros
            totalRecord = data.FirstOrDefault() == null ? 0 : data.FirstOrDefault().Total;

            ////Almacena el subtotal de registro en caso de obtener un parámetro de búsqueda
            filterRecord = string.IsNullOrEmpty(request.Busqueda) ? totalRecord : data.Count();

            var List = new List<vEquipoResponseGrid>();
            foreach (var row in data)
            {
                List.Add(new vEquipoResponseGrid
                {
                    Id = row.Id,
                    NombreLinea = row.NombreLinea,
                    NumeroSerie = row.NumeroSerie,
                    IdCatEstatusEquipo = row.IdCatEstatusEquipo,
                    NombreEquipo = row.NombreEquipo,
                    IdUserRegistro = row.IdUserRegistro,
                    Nombre = row.Nombre,
                    FechaRegistro = row.FechaRegistro,
                    FechaProximaCalibracion = row.FechaProximaCalibracion,
                    Estatus = row.Estatus,
                    Acciones = await this.RenderViewToStringAsync("~/Views/Equipo/_Acciones.cshtml", row)
                });
            }
            var returnObj = new
            {
                draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = List
            };

            return Json(returnObj);
        }

        [HttpGet]
        public async Task<IActionResult> Detalle(long id)
        {
            var listaResult = await EquipoHelper.Detalle(_proxyWebAPI, id);
            if (!listaResult.IsSuccessFully)
                return BadRequest();
            var vm = listaResult.Result as vEquipoResponse ?? new vEquipoResponse();
            var VBUrlDoc1 = "";
            var VBUrlDoc2 = "";
            var VBUrlDoc3 = "";
            var VBUrlDoc4 = "";
            if (!string.IsNullOrEmpty(vm.UrlFactura))
            {
                var arrDoc = vm.UrlFactura.Split("/");
                var NameDoc1 = arrDoc[arrDoc.Length - 1];
                var ContentType1 = NameDoc1.Contains(".pdf") ? "data:application/pdf;base64," : "data:image/png;base64,";
                var archivo = await _blobStorage.DownloadFileAsync(vm.UrlFactura, true);
                if (archivo.IsSuccessFully)
                {
                    var imageUrlFactura = string.Format("{0}{1}", ContentType1, archivo.Result);
                    VBUrlDoc1 = imageUrlFactura;
                }
            }
            if (!string.IsNullOrEmpty(vm.UrlManualUsuario))
            {
                var arrDoc = vm.UrlManualUsuario.Split("/");
                var NameDoc1 = arrDoc[arrDoc.Length - 1];
                var ContentType1 = NameDoc1.Contains(".pdf") ? "data:application/pdf;base64," : "data:image/png;base64,";
                var archivo = await _blobStorage.DownloadFileAsync(vm.UrlManualUsuario, true);
                if (archivo.IsSuccessFully)
                {
                    var imageUrlManualUsuario = string.Format("{0}{1}", ContentType1, archivo.Result);
                    VBUrlDoc2 = imageUrlManualUsuario;
                }
            }
            if (!string.IsNullOrEmpty(vm.UrlEspecificacionTecnica))
            {
                var arrDoc = vm.UrlEspecificacionTecnica.Split("/");
                var NameDoc1 = arrDoc[arrDoc.Length - 1];
                var ContentType1 = NameDoc1.Contains(".pdf") ? "data:application/pdf;base64," : "data:image/png;base64,";
                var archivo = await _blobStorage.DownloadFileAsync(vm.UrlEspecificacionTecnica, true);
                if (archivo.IsSuccessFully)
                {
                    var imageUrlEspecificacionTecnica = string.Format("{0}{1}", ContentType1, archivo.Result);
                    VBUrlDoc3 = imageUrlEspecificacionTecnica;
                }
            }
            if (!string.IsNullOrEmpty(vm.UrlRecomendacionServicio))
            {
                var arrDoc = vm.UrlRecomendacionServicio.Split("/");
                var NameDoc1 = arrDoc[arrDoc.Length - 1];
                var ContentType1 = NameDoc1.Contains(".pdf") ? "data:application/pdf;base64," : "data:image/png;base64,";
                var archivo = await _blobStorage.DownloadFileAsync(vm.UrlRecomendacionServicio, true);
                if (archivo.IsSuccessFully)
                {
                    var imageUrlRecomendacionServicio = string.Format("{0}{1}", ContentType1, archivo.Result);
                    VBUrlDoc4 = imageUrlRecomendacionServicio;
                }
            }
            ViewBag.UrlFactura = VBUrlDoc1;
            ViewBag.UrlManualUsuario = VBUrlDoc2;
            ViewBag.UrlEspecificacionTecnica = VBUrlDoc3;
            ViewBag.UrlRecomendacionServicio = VBUrlDoc4;
            return View("~/Views/Equipo/Detalle.cshtml", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Detalle([FromBody] AuxEstatusResponse request)
        {
            var result = new JsonResultDto();
            try
            {
                if (request.Id > 0)
                {
                    var save = await EquipoHelper.ActualizarEstatus(_proxyWebAPI, request);
                    if (!save.IsSuccessFully)
                    {
                        result.Error = true;
                        result.ErrorDescription = _mensajeErrorCatch;
                    }
                    else
                    {
                        result.Error = false;
                        result.ErrorDescription = save.Message ?? "La información se actualizó correctamente";
                    }
                }
                return Json(result);
            }
            catch (Exception ex)
            {
                result.Error = true;
                result.ErrorDescription = _mensajeErrorCatch;
            }

            return Json(result);
        }

        // [HttpGet]
        // public async Task<IActionResult> Registro(long? id)
        // {
        //     var result = new ResponseViewModel(true);
        //     try
        //     {
        //         ViewBag.TiposEquipo = EquiposDict.Equipos.Select(x => new SelectListItem { Value = x.Key.ToString(), Text = x.Value }).ToList();
        //         var lineas = await EquipoHelper.ConsultaLinea(_proxyWebAPI, new LineaRequest() { Activo = true });
        //         if (lineas.IsSuccessFully)
        //         {
        //             ViewBag.lineas = ((List<LineaResponse>)lineas.Result).Select(obj => new SelectListItem { Value = obj.Id.ToString(), Text = obj.Nombre }).ToList();
        //         }
        //         ViewBag.Enabled = true;
        //         return View("~/Views/Equipo/Registro.cshtml");
        //     }
        //     catch (Exception ex)

Smadot.Web/Views/Equipo/Index.cshtml
@using Smadot.Models.Dicts;
@inject Smadot.Utilities.GestionTokens.IUserResolver UserResolver
@{
    ViewData["Title"] = "Inventario";
    Layout = "~/Views/Shared/_LayoutSmadot.cshtml";
}

@section styles {
    <link rel="stylesheet" href="~/lib/datatable/dist/css/dataTables.bootstrap4.min.css" />
    <style>
        input:read-only {
            pointer-events: none;
            background: var(--kt-input-disabled-bg);
        }

    </style>
}

@section breadcrumb {
    <li class="breadcrumb-item">
        <a href="#" class="text-muted text-hover-primary">Seguimiento a Centros de Verificación</a>
    </li>
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <li class="breadcrumb-item">
        <a href="#" class="text-muted text-hover-primary">Equipos</a>
    </li>
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <li class="active">@ViewData["Title"]</li>
}


@section toolbar {
    @if (UserResolver.HasPermission(MenuInventarioEquipos.Registrar))
    {
        <a class="btn btn-sm fw-bold btn-primary" href="javascript:void();" type="button" id="save">Registrar </a>
    }
}

<div class="row">
    <!--begin::Col-->
    <div class="col-md-12">
        <!--begin::List widget 1-->
        <div class="card card-flush h-lg-100">
            <!--begin::Body-->
            <div class="card-body pt-5">
                <div class="bottom-buffer">
                    <div class="datatable datatable-bordered cell-border datatable-head-custom">
                        <table class="table table-striped gx-7" id="kt_datatable"></table>
                    </div>
                </div>
            </div>
            <!--end::Body-->
        </div>
        <!--end::LIst widget 1-->
    </div>
    <!--end::Col-->
</div>

<partial name="~/Views/Shared/_ModalRegistro.cshtml" model="string.Empty" />
<partial name="~/Views/Shared/_ModalNotificacion.cshtml" model="string.Empty" />

@section Scripts {
    <script src="~/lib/datatable/dist/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatable/dist/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/moment/js/moment-with-locales.js"></script>
    <script src="~/lib/formvalidation/dist/js/FormValidation.full.min.js"></script>
    <script src="~/lib/daterangepicker/js/daterangepicker.js"></script>
    <script src="~/js/Equipo/smadot.equipo.index.js" asp-append-version="true"></script>
    <script src="~/js/Equipo/smadot.equipo.registro.js" asp-append-version="true"></script>
}

Smadot.Web/Views/Equipo/_Acciones.cshtml
@using Smadot.Models.Dicts;
@inject Smadot.Utilities.GestionTokens.IUserResolver UserResolver
@model Smadot.Models.Entities.Equipo.Response.vEquipoResponse

<div class="btn-group dropup drop-up dropdown">
    <a href="javascript:;" class="btn btn-sm btn-secondary btn-text-primary btn-hover-primary btn-icon mr-2"
        data-bs-toggle="dropdown">
        <i class="bi bi-three-dots"></i>
    </a>
    <ul class="dropdown-menu">
        <li>
            <h6 class="dropdown-header">Selecciona una acción:</h6>
        </li>
        <li>
            <a class="editar" data-id="@Model.Id">
                <label class="dropdown-item">
                    <span class="navi-icon"><i class="bi bi-pencil-square"></i></span>&nbsp;&nbsp;
                    <span class="navi-text">Editar</span>
                </label>
            </a>
        </li>
        @if (UserResolver.HasPermission(MenuInventarioEquipos.Detalle))
        {
            <li>
                <a class="btnDetalle" asp-action="Detalle" asp-controller="Equipo" asp-route-id="@Model.Id">
                    <label class="dropdown-item">
                        <span class="navi-icon"><i class="bi bi-search"></i></span>&nbsp;&nbsp;
                        <span class="navi-text">Detalle</span>
                    </label>
                </a>
            </li>
        }
        @if (UserResolver.HasPermission(MenuInventarioEquipos.ProgramaciondeCalibracion))
        {
            @if (Model.IdCatEstatusEquipo != 1)
            {
                <li>
                    <a class="btnProgramacionCalibracion" asp-action="Index" asp-controller="ProgramacionCalibracion"
                        asp-route-id="@Model.Id">
                        <label class="dropdown-item">
                            <span class="navi-icon"><i class="bi bi-file-earmark-text"></i></span>&nbsp;&nbsp;
                            <span class="navi-text">Programación de Calibración</span>
                        </label>
                    </a>
                </li>
            }
        }

    </ul>
</div>