Smadot.Web/Controllers/EstatusDeUso/FoliosRegresadosSPFController.cs
using Microsoft.AspNetCore.Mvc;
using Smadot.Utilities.Reporting.Interfaces;
using Smadot.Models.Entities.FoliosRegresadosSPF.Request;
using Smadot.Models.Entities.FoliosRegresadosSPF.Response;
using Smadot.Models.Entities.Generic.Response;
using Smadot.Utilities.Modelos.Documentos;
using Smadot.Utilities.ProxyWebAPI.Interfaces;
using Smadot.Web.Helper.Operaciones.SolicitudFormaValorada;
using Smadot.Web.Models;
using Smadot.Web.Utilities;
using Smadot.Web.Handler.Autorizacion;
using Smadot.Utilities.GestionTokens;
using Smadot.Models.Dicts;

namespace Smadot.Web.Controllers.EstatusDeUso
{
    [Authorize]
    public class FoliosRegresadosSPFController : Controller
    {
        private readonly IProxyWebAPI _proxyWebAPI;
        private readonly IPdfBuider _pdfBuilder;
        private readonly IExcelBuilder _excelBuilder;
        private readonly IUserResolver _userResolver;

        //Mensaje genérico de error
        public string _mensajeErrorCatch = "Ocurrió un error al realizar la operación";

        public FoliosRegresadosSPFController(IProxyWebAPI proxyWebAPI, IPdfBuider pdfBuider, IExcelBuilder excelBuilder, IUserResolver userResolver)
        {
            _proxyWebAPI = proxyWebAPI;
            _pdfBuilder = pdfBuider;
            _excelBuilder = excelBuilder;
            _userResolver = userResolver;
        }

        public IActionResult Index()
        {
            if (!_userResolver.HasPermission(PermisosMenu.FoliosRegresadosaSPF))
                return new UnauthorizedResult();
            return View("~/Views/EstatusDeUso/FoliosRegresadosSPF/Index.cshtml");
        }

        [HttpPost]
        public async Task<JsonResult> Consulta()
        {
            JsonResult result = new JsonResult("");

            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var page = skip / pageSize + 1;

            var request = new FoliosRegresadosSPFRequest();
            request.Pagina = page;
            request.Registros = pageSize;
            request.Busqueda = searchValue;
            request.ColumnaOrdenamiento = sortColumn;
            request.Ordenamiento = sortColumnDirection;

            var listaResult = await SolicitudFormaValoradaHelper.ConsultaFoliosRegresadosSPF(_proxyWebAPI, request);
            var data = listaResult.Result as List<FoliosRegresadosSPFResponse> ?? new List<FoliosRegresadosSPFResponse>();

            //Almacena el total de registros
            totalRecord = data.FirstOrDefault() == null ? 0 : data.FirstOrDefault().Total;

            //Almacena el subtotal de registro en caso de obtener un parámetro de búsqueda
            filterRecord = string.IsNullOrEmpty(searchValue) ? totalRecord : data.Count();

            var List = new List<FoliosRegresadosSPFResponseGrid>();
            foreach (var row in data)
            {
                List.Add(new FoliosRegresadosSPFResponseGrid()
                {
                    ClaveDevolucion = row.ClaveDevolucion,
                    ClaveSolicitud = row.ClaveSolicitud,
                    Fecha = row.Fecha,
                    TipoCertificado = row.TipoCertificado,
                    ClaveCertificado = row.ClaveCertificado,
                    FolioInicial = row.FolioInicial,
                    FolioFinal = row.FolioFinal,
                    ResponsableEntrega = row.ResponsableEntrega,
                    PersonaValido = row.PersonaValido,
                    Acciones = await this.RenderViewToStringAsync("~/Views/EstatusDeUso/FoliosRegresadosSPF/_Acciones.cshtml", row)
                });
            }

            var returnObj = new
            {
                draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = List
            };

            return Json(returnObj);
        }

        [HttpGet]
        public async Task<JsonResult> DetalleFolioRegresado(long id)
        {
            var result = new ResponseViewModel(true);
            var vm = new FoliosRegresadosSPFResponse();
            try
            {
                var response = await SolicitudFormaValoradaHelper.DetalleFolioRegresadoSPF(_proxyWebAPI, id);
                if (!response.IsSuccessFully)
                {
                    result.IsSuccessFully = false;
                    return new JsonResult(result);
                }
                vm = response.Result as FoliosRegresadosSPFResponse ?? vm;
                result.Result = await this.RenderViewToStringAsync("~/Views/EstatusDeUso/FoliosRegresadosSPF/_ModalDetalle.cshtml", vm);
            }
            catch (Exception ex)
            {
                result.IsSuccessFully = false;
                result.Message = ex.Message;
            }
            return new JsonResult(result);
        }

        #region Reportes
        [HttpGet]
        public async Task<IActionResult> CrearReporte(string search, string sortColumnDirection, string sortColumn, bool esReportePdf)
        {
            JsonResultDto result = new JsonResultDto();

            try
            {
                var request = new FoliosRegresadosSPFRequest
                {
                    Busqueda = search,
                    ColumnaOrdenamiento = sortColumn,
                    Ordenamiento = sortColumnDirection,
                    Pagination = true
                };

                var listaResult = await SolicitudFormaValoradaHelper.ConsultaFoliosRegresadosSPF(_proxyWebAPI, request);
                var dataResult = listaResult.Result as List<FoliosRegresadosSPFResponse> ?? new List<FoliosRegresadosSPFResponse>();

                var data = dataResult.Select(x => new FoliosRegresadosSPFDocument()
                {
                    ClaveCertificado = x.ClaveCertificado,
                    FolioFinal = x.FolioFinal,
                    FolioInicial = x.FolioInicial,
                    PersonaValido = x.PersonaValido,
                    ResponsableEntrega = x.ResponsableEntrega,
                    TipoCertificado = x.TipoCertificado,
                    Fecha = x.Fecha
                }).ToList();

                byte[] bytes;
                if (esReportePdf)
                {
                    var reportePDF = await _pdfBuilder.GetDocumentoFoliosRegresadosSPF(data);
                    bytes = reportePDF.Response.DocumentoPDF;
                    return File(bytes, "application/pdf", reportePDF.Response.NombreDocumento);
                }
                else
                {
                    var reporteExcel = await _excelBuilder.GetDocumentoFoliosRegresadosSPF(data);
                    bytes = reporteExcel.Response.DocumentoExcel;
                    HttpContext.Session.SetString("FileName", reporteExcel.Response.NombreDocumento);
                    HttpContext.Session.Set("FileXlsx", bytes);
                }
                result.Result = new
                {
                    FileName = "Folios regresados a SPF",
                    Bytes = bytes
                };
            }
            catch (Exception ex)
            {
                result.Error = true;
                result.ErrorDescription = $"Error al generar el reporte | {ex.Message} --- {ex.StackTrace}";
            }
            return Json(result);
        }

        #endregion Reportes
    }
}

Smadot.Web/Controllers/EstatusDeUso/FoliosVendidosCentrosVerificacionController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Smadot.Utilities.Reporting.Interfaces;
using Smadot.Models.DataBase;
using Smadot.Models.Entities.FoliosVendidosCentrosVerificacion.Request;
using Smadot.Models.Entities.FoliosVendidosCentrosVerificacion.Response;
using Smadot.Models.Entities.Generic.Response;
using Smadot.Utilities.Modelos;
using Smadot.Utilities.Modelos.Documentos;
using Smadot.Utilities.ProxyWebAPI.Interfaces;
using Smadot.Web.Helper.Operaciones.SolicitudFormaValorada;
using Smadot.Web.Models;
using Smadot.Web.Utilities;
using Smadot.Web.Handler.Autorizacion;
using Smadot.Models.Dicts;
using Smadot.Utilities.GestionTokens;

namespace Smadot.Web.Controllers.EstatusDeUso
{
    [Authorize]
    public class FoliosVendidosCentrosVerificacionController : Controller
    {
        private readonly IProxyWebAPI _proxyWebAPI;
        private readonly IPdfBuider _pdfBuilder;
        private readonly IExcelBuilder _excelBuilder;
        private readonly IUserResolver _userResolver;

        //Mensaje genérico de error
        public string _mensajeErrorCatch = "Ocurrió un error al realizar la operación";

        public FoliosVendidosCentrosVerificacionController(IProxyWebAPI proxyWebAPI, IPdfBuider pdfBuilder, IExcelBuilder excelBuilder, IUserResolver userResolver)
        {
            _proxyWebAPI = proxyWebAPI;
            _pdfBuilder = pdfBuilder;
            _excelBuilder = excelBuilder;
            _userResolver = userResolver;
        }

        public IActionResult Index()
        {
            if (!_userResolver.HasPermission(PermisosMenu.FoliosVendidosaCentrosdeVerificacion))
                return new UnauthorizedResult();
            return View("~/Views/EstatusDeUso/FoliosVendidosCentrosVerificacion/Index.cshtml");
        }

        [HttpPost]
        public async Task<JsonResult> Consulta()
        {
            JsonResult result = new JsonResult("");

            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var page = skip / pageSize + 1;

            //Invoca al método que se encarga de realizar la petición Api
            var request = new FoliosVendidosCentrosVerificacionRequest();
            request.Pagina = page;
            request.Registros = pageSize;
            request.Busqueda = searchValue;
            request.ColumnaOrdenamiento = sortColumn;
            request.Ordenamiento = sortColumnDirection;

            var listaResult = await SolicitudFormaValoradaHelper.ConsultaFoliosVendidosCentrosVerificacion(_proxyWebAPI, request);
            var data = listaResult.Result as List<FoliosVendidosCentrosVerificacionResponse> ?? new List<FoliosVendidosCentrosVerificacionResponse>();

            //Almacena el total de registros
            totalRecord = data.FirstOrDefault() == null ? 0 : data.FirstOrDefault().TotalRegistros;

            //Almacena el subtotal de registro en caso de obtener un parámetro de búsqueda
            filterRecord = string.IsNullOrEmpty(searchValue) ? totalRecord : data.Count();

            var List = new List<FoliosVendidosCentrosVerificacionsResponseGrid>();
            foreach (var row in data)
            {
                List.Add(new FoliosVendidosCentrosVerificacionsResponseGrid()
                {
                    Fecha = row.Fecha,
                    CVV = row.CVV,
                    FolioVenta = row.FolioVenta,
                    FolioFV = row.FolioFV,
                    PersonaRecibeCertificado = row.PersonaRecibeCertificado,
                    ClaveVenta = row.ClaveVenta,
                    Total = row.Total,
                    FoliosStock = row.FoliosStock,
                    MontoCadaVenta = row.MontoCadaVenta,
                    ReferenciaBancaria = row.ReferenciaBancaria,
                    Acciones = await this.RenderViewToStringAsync("~/Views/EstatusDeUso/FoliosVendidosCentrosVerificacion/_Acciones.cshtml", row)
                });
            }

            var returnObj = new
            {
                draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = List
            };

            return Json(returnObj);
        }

        [HttpGet]
        public async Task<JsonResult> DetalleFolioVendido(long id)
        {
            var result = new ResponseViewModel(true);
            var vm = new FoliosVendidosCentrosVerificacionResponse();
            try
            {
                var response = await SolicitudFormaValoradaHelper.DetalleFoliosVendidosCentrosVerificacion(_proxyWebAPI, id);
                if (!response.IsSuccessFully)
                {
                    result.IsSuccessFully = false;
                    return new JsonResult(result);
                }
                vm = response.Result as FoliosVendidosCentrosVerificacionResponse ?? vm;
                result.Result = await this.RenderViewToStringAsync("~/Views/EstatusDeUso/FoliosVendidosCentrosVerificacion/_ModalDetalle.cshtml", vm);
            }
            catch (Exception ex)
            {
                result.IsSuccessFully = false;
                result.Message = ex.Message;
            }
            return new JsonResult(result);
        }

        #region Reportes

        [HttpGet]
        public async Task<IActionResult> CrearReporte(string search, string sortColumnDirection, string sortColumn, bool esReportePdf)
        {
            JsonResultDto result = new JsonResultDto();
            ResponseGeneric<DataExcelReport> reporteExcel = new();
            try
            {
                var request = new FoliosVendidosCentrosVerificacionRequest
                {
                    Busqueda = search,
                    ColumnaOrdenamiento = sortColumn,
                    Ordenamiento = sortColumnDirection,
                    Pagination = true
                };

                var listaResult = await SolicitudFormaValoradaHelper.ConsultaFoliosVendidosCentrosVerificacion(_proxyWebAPI, request);
                var dataResult = listaResult.Result as List<FoliosVendidosCentrosVerificacionResponse> ?? new List<FoliosVendidosCentrosVerificacionResponse>();

                var data = dataResult.Select(x => new FoliosVendidosCentroVerificacionDocument()
                {
                    FolioVenta = x.FolioVenta,
                    ClaveVenta = x.ClaveVenta,
                    FolioFV = x.FolioFV,
                    FoliosStock = x.FolioFV,
                    ReferenciaBancaria = x.ReferenciaBancaria,
                    MontoCadaVenta = x.MontoCadaVenta,
                    Fecha = x.Fecha
                }).ToList();

                byte[] bytes;
                if (esReportePdf)
                {
                    var reportePDF = await _pdfBuilder.GetDocumentoFoliosVendidosCentroVerificacion(data);
                    bytes = reportePDF.Response.DocumentoPDF;
                    return File(bytes, "application/pdf", reportePDF.Response.NombreDocumento);
                }
                else
                {
                    reporteExcel = await _excelBuilder.GetDocumentoFoliosVendidosCentroVerificacion(data);
                    bytes = reporteExcel.Response.DocumentoExcel;
                    HttpContext.Session.SetString("FileName", reporteExcel.Response.NombreDocumento);
                    HttpContext.Session.Set("FileXlsx", bytes);
                }
                result.Result = new
                {
                    FileName = "Folios vendidos en centros de verificación",
                    Bytes = bytes
                };
            }
            catch (Exception ex)
            {
                result.Error = true;
                result.ErrorDescription = $"Error al generar el reporte | {ex.Message} --- {ex.StackTrace} --- { JsonConvert.SerializeObject( new { reporteExcel, result } ) }";
            }
            return Json(result);
        }

        [HttpGet]
        public async Task<FileResult> DescargarReporte()
        {
            var fileName = HttpContext.Session.GetString("FileName");
            var bytes = HttpContext.Session.Get("FileXlsx");

            HttpContext.Session.Remove("FileName");
            HttpContext.Session.Remove("FileXlsx");

            return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
        }

        #endregion Reportes
    }
}

Smadot.Web/Views/EstatusDeUso/FoliosRegresadosSPF/Index.cshtml
@using Smadot.Models.Dicts;
@inject Smadot.Utilities.GestionTokens.IUserResolver UserResolver
@{
    Layout = "~/Views/Shared/_LayoutSmadot.cshtml";
    ViewData["Title"] = "Folios regresados a SPF";
}

@section styles{
    <link rel="stylesheet" href="~/assets/plugins/custom/datatables/datatables.bundle.css" />
    <style>
        input:read-only {
            pointer-events: none;
            background: var(--kt-input-disabled-bg);
        }
    </style>
}
    @section breadcrumb{
    <li class="breadcrumb-item text-muted">
        <a href="#" class="text-muted text-hover-primary">Administrar formas valoradas</a>
    </li>
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <li class="breadcrumb-item text-muted">
        <a href="#" class="text-muted text-hover-primary">Estatus de uso</a>
    </li>
    <li class="breadcrumb-item">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <li class="breadcrumb-item">
        <a href="#" class="text-hover-primary">@ViewData["Title"]</a>
    }

    @section toolbar{
    @if (UserResolver.HasPermission(MenuFoliosRegresadosSPF.Exportar))
    {
    <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
            <a href='@Url.Action("DescargarReporte","FoliosVendidosCentrosVerificacion")' id="linkDownloadReport" style="display:none"></a>
            <button type="button" class="btn btn-sm fw-bold btn-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
                Exportar
            </button>
            <div id="kt_datatable_export_menu" class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-200px py-4" data-kt-menu="true">
                <div class="menu-item px-3">
                    <a href="#" class="menu-link px-3" data-kt-export="excel">
                        <i class="las la-file-excel"></i>&nbsp;&nbsp;
                        Exportar a Excel
                    </a>
                </div>
                <div class="menu-item px-3">
                    <a href="#" class="menu-link px-3" data-kt-export="pdf">
                        <i class="las la-file-pdf"></i>&nbsp;&nbsp;
                        Exportar a PDF
                    </a>
                </div>
            </div>
            <div id="kt_datatable_buttons" class="d-none"></div>
        </div>
    }
    }

        <div class="row">
            <div class="col-md-12">
                <div class="card card-flush h-lg-100">
                    <div class="card-body pt-5">
                        <div class="bottom-buffer">
                            <div class="datatable datatable-bordered datatable-head-custom">
                                <div class="card card-p-0 card-flush">
                                    <div class="card-body">
                                        <div class="d-flex align-items-center position-relative my-1 justify-content-end">
                                            <input type="text" data-kt-filter="search" class="form-control form-control-sm w-250px mb-6" placeholder="Buscar" />
                                        </div>
                                        <table class="table align-middle border rounded table-row-dashed fs-6 g-5" id="kt_datatable">                                            
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <partial name="~/Views/Shared/_ModalRegistro.cshtml" model="string.Empty" />
        <partial name="~/Views/Shared/_ModalNotificacion.cshtml" model="string.Empty" />

    @section Scripts{
        <script src="~/assets/plugins/custom/datatables/datatables.bundle.js"></script>
        <script src="~/lib/moment/js/moment-with-locales.js"></script>
        <script src="~/lib/daterangepicker/js/daterangepicker.js"></script>
        <script src="~/lib/es6-shim/dist/es6-shim.min.js"></script>
        <script src="~/lib/formvalidation/dist/js/FormValidation.full.min.js"></script>
        <script src="~/js/EstatusDeUso/folios.regresados.spf.index.js" asp-append-version="true"></script>
    }

Smadot.Web/Views/EstatusDeUso/FoliosRegresadosSPF/_Acciones.cshtml
@using Smadot.Models.Dicts;
@inject Smadot.Utilities.GestionTokens.IUserResolver UserResolver
@model Smadot.Models.Entities.FoliosRegresadosSPF.Response.FoliosRegresadosSPFResponse
<div class="btn-group dropup drop-up dropdown">
    <a href="javascript:;" class="btn btn-sm btn-secondary btn-text-primary btn-hover-primary btn-icon mr-2" data-bs-toggle="dropdown">         
        <i class="bi bi-three-dots"></i>         
    </a> 
    <ul class="dropdown-menu">  
        <li><h6 class="dropdown-header">Selecciona una acción:</h6></li>        
        @if (UserResolver.HasPermission(MenuFoliosRegresadosSPF.Detalle))
        {
            <li>
                <a class="btnDetalle" data-id="@Model.IdFormaValorada">
                    <label class="dropdown-item">
                        <span class="navi-icon"><i class="bi bi-search"></i></span>&nbsp;&nbsp;
                        <span class="navi-text">Detalle</span>
                    </label>
                </a>
            </li>
        }
    </ul>     
</div>

Smadot.Web/Views/EstatusDeUso/FoliosRegresadosSPF/_ModalDetalle.cshtml
@model Smadot.Models.Entities.FoliosRegresadosSPF.Response.FoliosRegresadosSPFResponse
<div class="d-flex">
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Clave de certificado</span>
        <div class="fw-semibold text-gray-400">@Model.ClaveCertificado</div>
    </div>
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Clave de devolución</span>
        <div class="fw-semibold text-gray-400">@Model.ClaveDevolucion</div>
    </div>
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Clave de solicitud</span>
        <div class="fw-semibold text-gray-400">@Model.ClaveSolicitud</div>
    </div>
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Clave de venta</span>
        <div class="fw-semibold text-gray-400">@Model.ClaveVenta</div>
    </div>
</div>
<div class="d-flex">
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Tipo de certificado</span>
        <div class="fw-semibold text-gray-400">@Model.TipoCertificado</div>
    </div>
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Folio inicial</span>
        <div class="fw-semibold text-gray-400">@Model.FolioInicial</div>
    </div>
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Folio final</span>
        <div class="fw-semibold text-gray-400">@Model.FolioFinal</div>
    </div>
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Responsable de entrega</span>
        <div class="fw-semibold text-gray-400">@Model.ResponsableEntrega</div>
    </div>
</div>
<div class="d-flex">    
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Persona que validó</span>
        <div class="fw-semibold text-gray-400">@Model.PersonaValido</div>
    </div>
    <div class="border border-gray-300 border-dashed rounded min-w-100px w-100 py-2 px-4 me-6 mb-3">
        <span class="fs-6 text-gray-700 fw-bold">Fecha</span>
        <div class="fw-semibold text-gray-400">@Model.Fecha.ToString("dd/MM/yyyy")</div>
    </div>
</div>