Smadot.Web/Controllers/Citas/CitasController.cs
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NPOI.Util;
using Smadot.FrontEnd.Models;
using Smadot.Models.DataBase;
using Smadot.Models.Entities.Cita.Request;
using Smadot.Models.Entities.FoliosFormaValorada.Response;
using Smadot.Models.Entities.Generic.Response;
using Smadot.Models.Entities.PortalCita.Response;
using Smadot.Utilities.BlobStorage;
using Smadot.Utilities.GestionTokens;
using Smadot.Utilities.Modelos;
using Smadot.Utilities.Modelos.Documentos;
using Smadot.Utilities.ProxyWebAPI.Interfaces;
using Smadot.Utilities.Reporting.Interfaces;
using Smadot.Utilities.Seguridad;
using Smadot.Web.Handler.Autorizacion;
using Smadot.Web.Helper.Operaciones;
using Smadot.Web.Helper.Operaciones.FoliosFormaValorada;
using Smadot.Web.Models;
using Smadot.Web.Utilities;

namespace Smadot.Web.Controllers.HistorialCitas
{

    public class CitasController : Controller
    {
        private readonly IProxyWebAPI _proxyWebAPI;
        private readonly IUserResolver _userResolver;
        private readonly IPdfBuider _pdfBuider;
        private readonly BlobStorage _blobStorage;
        private string _llaveCifrado;
        private readonly IExcelBuilder _excelBuilder;
        public CitasController(IProxyWebAPI proxyWebAPI, IUserResolver userResolver, IPdfBuider pdfBuider, IConfiguration configuration, IExcelBuilder excelBuilder)
        {
            _proxyWebAPI = proxyWebAPI;
            _userResolver = userResolver;
            _pdfBuider = pdfBuider;
            _llaveCifrado = configuration["Encrypter:ClaveSecreta"];
            _blobStorage = new BlobStorage(configuration["ConnectionBlobStrings:BlobString"], configuration["ConnectionBlobStrings:Container"]);
            _excelBuilder = excelBuilder;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View("~/Views/Citas/Index.cshtml");

        }
        [Authorize]
        [HttpPost]
        public async Task<JsonResult> Consulta(string fecha1, string fecha2, bool? atendida)
        {
            JsonResult result = new JsonResult("");

            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int page = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");

            //Invoca al método que se encarga de realizar la petición Api
            var request = new CitaGridRequest();
            request.Pagina = page / pageSize + 1;
            request.Registros = pageSize;
            request.Busqueda = string.IsNullOrEmpty(searchValue) ? null : searchValue;
            request.ColumnaOrdenamiento = sortColumn;
            request.Ordenamiento = sortColumnDirection;
            request.Atendida = atendida;
            DateTime fecharesult;
            string formatoFecha = "dd/MM/yyyy";
            if (DateTime.TryParseExact(fecha1, formatoFecha, CultureInfo.InvariantCulture, DateTimeStyles.None, out fecharesult))
            {
                request.Fecha1 = fecharesult;
            }
            else
            {
                request.Fecha1 = null;
            }
            if (DateTime.TryParseExact(fecha2, formatoFecha, CultureInfo.InvariantCulture, DateTimeStyles.None, out fecharesult))
            {
                request.Fecha2 = fecharesult;
            }
            else
            {
                request.Fecha2 = null;
            }
            var response = await CitasHelper.Consulta(_proxyWebAPI, request);

            if (response.IsSuccessFully)
            {
                var jsonReponse = (ResponseGrid<HistorialCitasResponse>)response.Result;
                jsonReponse.Data.ForEach(async x =>
                {
                    x.Acciones = await this.RenderViewToStringAsync("~/Views/Citas/_Acciones.cshtml", x);
                });
                jsonReponse.Draw = draw;
                return Json(jsonReponse);
            }

            return Json("");
        }
        [Authorize]
        public async Task<IActionResult> Expediente(long id)
        {
            var citaHelper = await CitasHelper.Expediente(_proxyWebAPI, id);
            var vm = new vVerificacionExpediente();
            if (citaHelper.IsSuccessFully)
            {
                vm = citaHelper.Result as vVerificacionExpediente ?? new vVerificacionExpediente();
                var listPdf = new List<ListDocumentos>();
                var listImage = new List<ListDocumentos>();


                if (!string.IsNullOrEmpty(vm.URLFotoTecnico))
                {

                    listImage.Add(new ListDocumentos
                    {
                        DocName = "Foto Técnico Verificador",
                        Extension = "imagen",
                        UrlName = vm.URLFotoTecnico.Contains(_blobStorage._url) ? vm.URLFotoTecnico.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                    });
                }

                if (!string.IsNullOrEmpty(vm.URLPlacaDelantera))
                {
                    listImage.Add(new ListDocumentos
                    {
                        DocName = "Placa Delantera",
                        Extension = "imagen",
                        UrlName = vm.URLPlacaDelantera.Contains(_blobStorage._url) ? vm.URLPlacaDelantera.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                    });
                }

                if (!string.IsNullOrEmpty(vm.URLPlacaTrasera))
                {

                    listImage.Add(new ListDocumentos
                    {
                        DocName = "Placa Trasera",
                        Extension = "imagen",
                        UrlName = vm.URLPlacaTrasera.Contains(_blobStorage._url) ? vm.URLPlacaTrasera.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                    });

                }

                if (!string.IsNullOrEmpty(vm.URLPlacaCamara))
                {
                    listImage.Add(new ListDocumentos
                    {
                        DocName = "Captura Cámara Delantera",
                        Extension = "imagen",
                        UrlName = vm.URLPlacaCamara.Contains(_blobStorage._url) ? vm.URLPlacaCamara.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                    });
                }
                if (!string.IsNullOrEmpty(vm.URLPlacaCamaraTrasera))
                {
                    listImage.Add(new ListDocumentos
                    {
                        DocName = "Captura Cámara Trasera",
                        Extension = "imagen",
                        UrlName = vm.URLPlacaCamaraTrasera.Contains(_blobStorage._url) ? vm.URLPlacaCamaraTrasera.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                    });
                }
                if (!string.IsNullOrEmpty(vm.URLEvidenciaFalla))
                {
                    listImage.Add(new ListDocumentos
                    {
                        DocName = "Evidencia Falla Inspección Visual",
                        Extension = "imagen",
                        UrlName = vm.URLEvidenciaFalla.Contains(_blobStorage._url) ? vm.URLEvidenciaFalla.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                    });
                }
                if (!string.IsNullOrEmpty(vm.URLIdentificacion))
                {
                    if (vm.URLIdentificacion.Contains(".pdf"))
                    {
                        listPdf.Add(new ListDocumentos
                        {
                            DocName = "Identificación",
                            Extension = "pdf",
                            UrlName = vm.URLIdentificacion.Contains(_blobStorage._url) ? vm.URLIdentificacion.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                        });
                    }
                    else
                    {
                        listImage.Add(new ListDocumentos
                        {
                            DocName = "Identificación",
                            Extension = "imagen",
                            UrlName = vm.URLIdentificacion.Contains(_blobStorage._url) ? vm.URLIdentificacion.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                        });
                    }
                }
                if (!string.IsNullOrEmpty(vm.URLFactura))
                {
                    if (vm.URLFactura.Contains(".pdf"))
                    {
                        listPdf.Add(new ListDocumentos
                        {
                            DocName = "Factura/Carta Factura",
                            Extension = "pdf",
                            UrlName = vm.URLFactura.Contains(_blobStorage._url) ? vm.URLFactura.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                        });
                    }
                    else
                    {
                        listImage.Add(new ListDocumentos
                        {
                            DocName = "Factura/Carta Factura",
                            Extension = "imagen",
                            UrlName = vm.URLFactura.Contains(_blobStorage._url) ? vm.URLFactura.Replace(string.Format("{0}/", _blobStorage._url), "") : ""
                        });
                    }
                }
                //if (!string.IsNullOrEmpty(vm.URLCartaFactura))
                //{
                //    if (vm.URLCartaFactura.Contains(".pdf"))
                //    {
                //        listPdf.Add(new ListDocumentos
                //        {

Smadot.Web/Views/EstadisiticaUsoFormaValorada/Index.cshtml
@{
    ViewData["Title"] = "Estadística de uso de formas valoradas";
    Layout = "~/Views/Shared/_LayoutSmadot.cshtml";
}
@section styles {
    <link rel="stylesheet" href="~/assets/plugins/custom/prismjs/prismjs.bundle.css" />
    <link rel="stylesheet" href="~/assets/plugins/custom/datatables/datatables.bundle.css" />
    <style>
        @*.table-responsive>table.dataTable.dtr-inline.collapsed>tbody>tr>td.dtr-control:before,table.dataTable.dtr-inline.collapsed>tbody>tr>th.dtr-control:before{top:1.3rem;left:95px;height:1.35rem;width:1.35rem;line-height:1.5;text-indent:-999px!important;margin-top:-0.675rem;margin-right:0.675rem;display:inline-block;position:relative;font-size:1.05rem;border:0;box-shadow:none;mask-size:85%;-webkit-mask-size:85%;content:".";}*@.table-responsive>.table.gs-7 td.dtr-control:first-child,
        .table.gs-7 th.dtr-control:first-child {
            padding-left: 0 !important;
        }


        .table-responsive>.table.gs-7 td.dtr-control:first-child,
        .table.gs-7 th.dtr-control:first-child {
            padding: 0.5rem 1.2rem !important;
            min-width: 80px;
        }

        main[role="main"] h1,
        main[role="main"] h2,
        main[role="main"] h3,
        main[role="main"] h4,
        main[role="main"] h5,
        main[role="main"] h6 p {
            margin-bottom: 0px !important;
        }

        .table.table-striped.gx-7.dataTable.no-footer tr th {
            font-weight: bold;
        }

        .bg-primary-smadsot {
            background: var(--kt-text-secondary) !important;
        }

        .bg-gray {
            background: #777 !important;
        }

        .card-folio>.symbol .text-secondary.bg-light-secondary {
            color: #8b704a !important;
            background: #e0ddd7 !important;
        }

        .card-folio>.symbol .text-orange.bg-light-orange {
            color: #f57d06 !important;
            background: #f8ddc2 !important;
        }

        .card-folio>.symbol .text-orange2.bg-light-orange2 {
            color: #f54e06 !important;
            background: rgb(251, 200, 188) !important;
        }
    </style>

}
<link rel="stylesheet" type="text/css" href="~/css/dashboard.css" />
@section breadcrumb {
    <li class="breadcrumb-item text-muted">Seguimiento a CVV</li>
    <li class="breadcrumb-item text-muted">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <li class="breadcrumb-item text-muted">Estadística</li>
    <li class="breadcrumb-item text-muted">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <li class="active">Dashboard</li>
}

@section toolbar {

    @*<div class="btn-group dropup drop-up dropdown">
<button class="btn btn-sm fw-bold btn-primary save" type="button" data-id="" id="save">Nuevo</button>
</div>*@


}
<div class="row">
    <div class="card card-flush h-lg-100 shadow-sm">
        <div class="card-body">
            <div class="row g-5 g-xl-5 flex-center py-4">
                <div class="col-xl-6">
                    <label class="form-label">Período</label>
                    <input class="form-control form-control-sm" placeholder="Selecciona un rango de fechas..."
                        id="kt_daterangepicker_1" />
                </div>
                <div class="col-xl-6">
                    <label class="form-label">Verificentro</label>
                    <select class="form-control form-select" asp-items="(List<SelectListItem>)ViewBag.CentroAtencion"
                        name="IdCentroAtencion" id="IdCentroAtencion">
                        <option value="">TODOS</option>
                    </select>
                </div>
            </div>
            <div class="row g-5 g-xl-5 flex-center py-4" id="indicadores-content">
            </div>
            <div class="row g-5 g-xl-5 flex-center py-4" id="indicadores-content">
                <h3 class="fs-4 fw-bold pe-2 pb-2">
                    Folios
                </h3>
                <div class="row" id="content-folios">

                </div>
            </div>
        </div>
    </div>
</div>

<div class="row g-5 g-xl-5 flex-center py-4">
    <div class="card h-lg-100 shadow-sm">
        <div class="card-header">
            <h3 class="card-title">
                Registro de Verificaciones
            </h3>

            <div class="card-toolbar">
                <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
                    <a href='@Url.Action("DescargarReporte","FoliosVendidosCentrosVerificacion")'
                        id="linkDownloadReport" style="display:none"></a>
                    <button type="button" class="btn btn-sm fw-bold btn-primary" data-kt-menu-trigger="click"
                        data-kt-menu-placement="bottom-end">
                        Exportar
                    </button>
                    <div id="kt_datatable_export_menu"
                        class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-200px py-4"
                        data-kt-menu="true">
                        <div class="menu-item px-3">
                            <a href="#" class="menu-link px-3" id="btnExport" data-kt-export="excel">
                                <i class="las la-file-excel"></i>&nbsp;&nbsp;
                                Exportar a Excel
                            </a>
                        </div>
                        @* <div class="menu-item px-3">
                        <a href="#" class="menu-link px-3" data-kt-export="pdf">
                        <i class="las la-file-pdf"></i>&nbsp;&nbsp;
                        Exportar a PDF
                        </a>
                        </div> *@
                    </div>
                    <div id="kt_datatable_buttons" class="d-none"></div>
                </div>
            </div>
        </div>
        <!--begin::Body-->
        <div class="card-body pt-5 ">
            <div class="row">

                <div class="my-5">
                    <div class="row">
                        <div class="col-lg-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label">Período</label>
                                <input class="form-control form-control-sm" id="grid_date_range" />
                            </div>
                        </div>
                        <div class="col-md-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label">Verificentro</label>
                                <select class="form-control form-select"
                                    asp-items="(List<SelectListItem>)ViewBag.CentroAtencion" name="IdVerificentro"
                                    id="IdVerificentro">
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label" for="hologramaGrid">Tipo Holograma</label>
                                <select class="form-control form-select" data-control="select2"
                                    asp-items="(List<SelectListItem>)ViewBag.TipoCertificado" name="hologramaGrid"
                                    id="hologramaGrid">
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label" for="rechazoGrid">Causa Rechazo</label>
                                <select class="form-control form-select" data-control="select2"
                                    asp-items="(List<SelectListItem>)ViewBag.CausaRechazo" name="rechazoGrid"
                                    id="rechazoGrid">
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label" for="rechazoGrid">Tipo de Servicio</label>
                                <select class="form-control form-select" data-control="select2"
                                    asp-items="(List<SelectListItem>)ViewBag.TiposServicio" name="TiposServicio"
                                    id="TiposServicio">
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label" for="rechazoGrid">Motivo de Verificación</label>
                                <select class="form-control form-select" data-control="select2"
                                    asp-items="(List<SelectListItem>)ViewBag.MotivosVerificacion"
                                    name="MotivosVerificacion" id="MotivosVerificacion">
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label" for="anioModeloGrid">Año Modelo Min.</label>
                                <input type="number" min="1920" max="@(DateTime.Now.Year+1)"
                                    class="form-control form-control-sm" id="ModeloMin" placeholder="Ingrese un año" />
                            </div>
                        </div>
                        <div class="col-md-3 pb-4">
                            <div class="form-group fv-row">
                                <label class="form-label" for="anioModeloGrid">Año Modelo Max.</label>
                                <input type="number" min="1920" max="@(DateTime.Now.Year+1)"
                                    class="form-control form-control-sm" id="ModeloMax" placeholder="Ingrese un año" />
                            </div>
                        </div>
                        <div class="d-flex flex-column flex-md-row-auto mb-md-0 mb-2 align-self-end">
                            <div class="d-flex flex-column-auto align-self-end">
                                <a class="btn btn-sm fw-bold btn-primary" id="btn-buscar">Buscar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped border rounded gy-5 gs-7 w-100" id="kt_datatable">
                </table>

            </div>
        </div>
        <!--end::Body-->
    </div>
</div>

<div class="row g-5 g-xl-5 flex-center py-4">
    <div class="card h-md-100" dir="ltr">
        <div class="card-header">
            <h3 class="card-title">
                Estadística
            </h3>
        </div>
        <!--begin::Body-->
        <div class="card-body d-flex justify-content-between flex-column">
            <div class="row g-5 g-xl-5 flex-center py-4">
                <div class="col-xl-6">
                    <label class="form-label">Período</label>
                    <input class="form-control form-control-sm" placeholder="Selecciona un rango de fechas..."
                        id="barchart_date_filter" />
                </div>
            </div>
            <div class="row g-5 g-xl-5 flex-center pb-4">
                <div class="col-lg-12">
                    <div class="fs-3 py-2 gray-700">Verificaciones por CVV</div>
                    <div class="bottom-buffer" id="div_Bar">
                        <div id="barchart_cvv" style="height: 330px;"></div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="fs-3 py-2 gray-700">Porcentaje de Solicitudes Por Trámite</div>

                    <div class="bottom-buffer">
                        <div id="kt_amcharts_3" style="width:100%;height: 330px;"></div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="fs-3 py-2 gray-700">Verificaciones por Certificado</div>
                    <div class="bottom-buffer">
                        <div id="kt_amcharts_5" style="width:100%;height: 330px;"></div>
                    </div>
                </div>
            </div>

        </div>
        <!--end::Body-->
    </div>
</div>



@section Scripts {
    <script src="~/assets/plugins/custom/prismjs/prismjs.bundle.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/percent.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/radar.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/plugins/exporting.js"></script>
    <script src="~/assets/plugins/custom/datatables/datatables.bundle.js"></script>
    <script src="~/js/AdministracionFormasValoradas/EstadisticaUsoFormasValoradas/index.js"
        asp-append-version="true"></script>
}

Smadot.Web/Views/EstadisiticaUsoFormaValorada/_actions.cshtml
@model Smadot.Models.Entities.SolicitudFormaValorada.Response.EstadisiticaUsoFormaValoradaResponseGridAcciones

<div class="btn-group dropup drop-up dropdown">
    <a href="javascript:;" class="btn btn-sm btn-secondary btn-text-primary btn-hover-primary btn-icon mr-2" data-bs-toggle="dropdown">
        <i class="bi bi-three-dots"></i>
    </a>
    <ul class="dropdown-menu">
        <li><h6 class="dropdown-header">Selecciona una acción:</h6></li>
        <li class="btnDetalle" data-id="">
            <a asp-action="Expediente" asp-controller="Citas" asp-route-id="@Model.Id">
                <label class="dropdown-item">

                    <span class="navi-icon"><i class="bi bi-zoom-in"></i></span>
                    <span class="navi-text">Detalle</span>

                </label>
            </a>
        </li>

    </ul>
</div>

Smadot.Web/Views/EstadisiticaUsoFormaValorada/_conteoCerificados.cshtml
@model List<Smadot.Models.Entities.SolicitudFormaValorada.Response.CertificadoMapeo>
@if (Model.Count == 0)
{
    <div class="row g-5 g-xl-5 flex-center py-4">
        <a href="javascript:void(0)" class="card hover-elevate-up shadow-sm parent-hover">
            <div class="card-body d-flex align-items">

                <span class="ms-3 text-gray-700 parent-hover-primary fs-5 fw-bold">
                    No hay nada que mostrar
                </span>
            </div>
        </a>
    </div>
}
@foreach (var item in Model)
{
    <div class="col-lg-3 col-3">
        <label class="btn btn-outline btn-outline-dashed btn-active-light-primary  d-flex align-items-center mb-5 card-folio"
            for="kt_create_account_form_account_type_personal">
            <div class="symbol symbol-65px symbol-circle mb-3 me-4">
                <span class="symbol-label fs-2x fw-semibold @Html.Raw(item.ClassNames)">@item.Simbolo</span>
            </div>
            <!--begin::Info-->
            <span class="d-block fw-semibold text-start">
                <span class="text-dark fw-bold d-block fs-4 mb-2">@item.Nombre</span>

                <span class="text-dark d-block fs-8">Total: <span class="text-dark d-block fs-4"
                        id="FolioDobleCero">@(item.Total)</span></span>
            </span>
            <!--end::Info-->
        </label>
        <!--end::Option-->
        <div class="fv-plugins-message-container invalid-feedback"></div>
    </div>

}

Smadot.Web/Views/EstadisiticaUsoFormaValorada/_indicadores.cshtml
@model Smadot.Models.Entities.SolicitudFormaValorada.Response.DashboardIndicadores
@if (Model.Totales.Count == 0)
{
    <div id="kt_carousel_2_carousel" class="carousel carousel-custom slide" data-bs-ride="carousel" data-bs-interval="8000">
        <!--begin::Heading-->
        <div class="d-flex align-items-center justify-content-between flex-wrap">
            <!--begin::Label-->
            <span class="fs-4 fw-bold pe-2">Indicadores</span>
            <!--end::Label-->
            <!--begin::Carousel Indicators-->
            <ol class="p-0 m-0 carousel-indicators carousel-indicators-dots">
                <li data-bs-target="#kt_carousel_2_carousel" data-bs-slide-to="0" class="active ms-1">
                </li>
            </ol>
            <div class="carousel-inner pt-8">
                <div class="carousel-item active">
                    <div class="row g-5 g-xl-5 flex-center py-4">
                        <a href="javascript:void(0)" class="card hover-elevate-up shadow-sm parent-hover">
                            <div class="card-body d-flex align-items">

                                <span class="ms-3 text-gray-700 parent-hover-primary fs-5 fw-bold">
                                    No hay nada que mostrar
                                </span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <!--end::Carousel Indicators-->
        </div>
    </div>
}
else
{
    <div id="kt_carousel_2_carousel" class="carousel carousel-custom slide" data-bs-ride="carousel" data-bs-interval="8000">
        <!--begin::Heading-->
        <div class="d-flex align-items-center justify-content-between flex-wrap">
            <!--begin::Label-->
            <span class="fs-4 fw-bold pe-2">Indicadores</span>
            <!--end::Label-->
            <!--begin::Carousel Indicators-->
            <ol class="p-0 m-0 carousel-indicators carousel-indicators-dots">
                @{
                    var k = 0;
                }
                @for (int i = 0; i < Model.Totales.Count; i += 4)
                {
                    <li data-bs-target="#kt_carousel_2_carousel" data-bs-slide-to="@(k.ToString())"
                        class="@((k == 0) ? "active" : "") ms-1">
                    </li>
                    k++;
                }
            </ol>
            <div class="carousel-inner pt-8">

                @for (int i = 0; i < Model.Totales.Count; i += 4)
                {
                    <div class="carousel-item @((i == 0) ? "active" : "")">
                        <div class="row g-5 g-xl-5 flex-center py-4">
                            @for (int j = i; j < Math.Min(i + 4, Model.Totales.Count); j++)
                            {
                                var item = Model.Totales[j];
                                <div class="col-xl-2">
                                    <!--begin::Statistics Widget 5-->
                                    <a href="#" class="card @(item.CssClass) hoverable mh-lg-170px mb-xl-4">
                                        <!--begin::Body-->
                                        <div class="card-body">
                                            <!--begin::Svg Icon | path: icons/duotune/general/gen032.svg-->
                                            <span class="svg-icon svg-icon-white svg-icon-3x ms-n1">
                                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <rect x="8" y="9" width="3" height="10" rx="1.5" fill="currentColor"></rect>
                                                    <rect opacity="0.5" x="13" y="5" width="3" height="14" rx="1.5"
                                                        fill="currentColor">
                                                    </rect>
                                                    <rect x="18" y="11" width="3" height="8" rx="1.5" fill="currentColor"></rect>
                                                    <rect x="3" y="13" width="3" height="6" rx="1.5" fill="currentColor"></rect>
                                                </svg>
                                            </span>
                                            <!--end::Svg Icon-->
                                            <div class="text-white fw-bold fs-2 CountNoCertificaciones">
                                                @(item.Total ?? "N/A")
                                            </div>
                                            <div class="fw-semibold text-white">@item.Nombre</div>
                                        </div>
                                        <!--end::Body-->
                                    </a>
                                    <!--end::Statistics Widget 5-->
                                </div>
                            }
                        </div>
                    </div>
                }
            </div>
            <!--end::Carousel Indicators-->
        </div>
    </div>
}