Smadot.Web/Controllers/SolicitudFormaValorada/FoliosCanceladosController.cs
using Microsoft.AspNetCore.Mvc;
using Smadot.Models.Entities.Generic.Response;
using Smadot.Models.Entities.SolicitudFormaValorada.Response;
using Smadot.Utilities.GestionTokens;
using Smadot.Utilities.Modelos;
using Smadot.Utilities.ProxyWebAPI.Interfaces;
using Smadot.Web.Utilities;
using static Smadot.Models.Entities.FoliosCancelados.Response.FoliosCanceladosResponseData;
using System.Linq.Dynamic.Core;
using System.Linq;
using Smadot.Web.Helper.Operaciones.SolicitudFormaValorada;
using Azure.Core;
using Smadot.Models.DataBase;
using static Smadot.Models.Entities.FoliosCancelados.Request.FoliosCanceladosRequestData;
using Smadot.Web.Models;
using Smadot.Web.Handler.Autorizacion;
using Smadot.Models.Dicts;
using Smadot.Web.Helper.Operaciones.Catalogo;
using Smadot.Models.Entities.Catalogos.Request;
using Smadot.Models.Entities.Catalogos.Response;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Smadot.Web.Controllers.SolicitudFormaValorada
{
    [Authorize]
    public class FoliosCanceladosController : Controller
    {
        private readonly IProxyWebAPI _proxyWebAPI;
        private readonly IUserResolver _userResolver;

        //Mensaje genérico de error
        public string _mensajeErrorCatch = "Ocurrió un error al realizar la operación";

        public FoliosCanceladosController(IProxyWebAPI proxyWebAPI, IUserResolver userResolver)
        {
            _proxyWebAPI = proxyWebAPI;
            _userResolver = userResolver;
        }

        public IActionResult Index()
        {
            if (!_userResolver.HasPermission(PermisosMenu.FoliosCancelados))
                return new UnauthorizedResult();
            return View("~/Views/FoliosCancelados/Index.cshtml");
        }

        [HttpPost]
        public async Task<JsonResult> Consulta()
        {
            JsonResult result = new JsonResult("");
            //Invoca al método que se encarga de realizar la petición Api
            var request = new RequestList();

            int totalRecord = 0;
            int filterRecord = 0;

            var draw = Request.Form["draw"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            request.Pagina = skip / pageSize + 1;
            request.Registros = pageSize;
            request.Busqueda = Request.Form["search[value]"].FirstOrDefault();
            request.ColumnaOrdenamiento = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            request.Ordenamiento = Request.Form["order[0][dir]"].FirstOrDefault();

            var gridData = new ResponseGrid<FoliosCanceladosResponseGrid>();
            var listaResult = await FoliosCanceladosHelper.Consulta(_proxyWebAPI, request);
            var data = listaResult.Result as List<FoliosCanceladosResponse> ?? new List<FoliosCanceladosResponse>();

            totalRecord = data.FirstOrDefault() == null ? 0 : data.FirstOrDefault().Total;

            filterRecord = string.IsNullOrEmpty(searchValue) ? totalRecord : data.Count();

            var List = new List<FoliosCanceladosResponseGrid>();

            foreach (var row in data)
            {
                List.Add(new FoliosCanceladosResponseGrid
                {
                    Folio = row.Folio,
                    FechaCancelacion = row.FechaCancelacion,
                    Motivo = (row.IdCatMotivoCancelacion == 3) ? string.IsNullOrEmpty(row.OtroMotivo) ? "Sin especificar" : row.OtroMotivo : row.Motivo,
                    UsuarioAprobo = row.UsuarioAprobo,
                    TipoTramite = row.TipoTramite,
                    DatosVehiculo = string.IsNullOrWhiteSpace(row.DatosVehiculo) ? null : row.DatosVehiculo,
                    PersonaRealizoTramite = row.PersonaRealizoTramite
                });
            }
            ////Almacena el subtotal de registro en caso de obtener un parámetro de búsqueda
            //var List = GetList();
            //var List = new List<FoliosCanceladosResponseGrid>();


            //if (!string.IsNullOrEmpty(request.Busqueda))
            //{
            //    List = List.Where(
            //        x => 
            //        x.Folio.ToLower().Contains(request.Busqueda.ToLower()) ||
            //        x.Motivo.ToLower().Contains(request.Busqueda.ToLower()) ||
            //        x.UsuarioAprobo.ToLower().Contains(request.Busqueda.ToLower()) || 
            //        x.TipoTramite.ToLower().Contains(request.Busqueda.ToLower())
            //        ).ToList();
            //}
            //if (!string.IsNullOrEmpty(request.ColumnaOrdenamiento) && !string.IsNullOrEmpty(request.Ordenamiento)) {
            //    var quer = List.AsQueryable();
            //    List = quer.OrderBy(request.ColumnaOrdenamiento + " " + request.Ordenamiento).ToList();

            //}

            //List.Add(new EstadisiticaUsoFormaValoradaResponse() { }, new EstadisiticaUsoFormaValoradaResponse() { });
            //gridData.Data = List;
            //gridData.RecordsTotal = totalRecord;
            //gridData.Data = gridData.Data.Skip(skip).Take(pageSize).ToList();
            //filterRecord = string.IsNullOrEmpty(request.Busqueda) ? gridData.RecordsTotal ?? 0 : gridData.Data.Count;
            //gridData.RecordsFiltered = filterRecord;
            //gridData.Draw = draw;

            var returnObj = new
            {
                draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = List
            };

            return Json(returnObj);
        }

        public async Task<IActionResult> Registro()
        {
			var catalogo = await TipoCertificadoHelper.Consulta(_proxyWebAPI, new TipoCertificadoRequest { Activo = true });
            var user = _userResolver.GetUser();
            var certificados = (catalogo.Result as List<TipoCertificadoResponse> ?? new List<TipoCertificadoResponse>());
            if (!user.ClaveVerificentro.Equals("SMADSOT-00"))
                certificados = certificados.Where(x => x.Id != TipoCertificado.Exentos && x.Id != TipoCertificado.Testificacion).ToList();
			ViewBag.Certificados = certificados.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Nombre }).ToList();
			return View("~/Views/FoliosCancelados/Registro.cshtml");
        }


        [HttpPost]
        public async Task<JsonResult> ConsultaFolioAutocomplete(string prefix)
        {
            //var folio = GetList().Where(x => x.Folio.ToLower().Contains(prefix)).Take(10).ToList();
            //var folio = GetList().Take(10).ToList();
            var listaResult = await FoliosCanceladosHelper.AutocompleteFolio(_proxyWebAPI, prefix);
            var folio = listaResult.Result as List<FoliosCanceladosAutoCompleteResponse> ?? new List<FoliosCanceladosAutoCompleteResponse>();
            var result = folio.Select(x => new { Id = x.Id, Nombre = x.Folio });
            return Json(result);
        }

        [HttpPost]
        public async Task<JsonResult> DetalleFolio(int id)
        {
            //var data = GetById(id);
            var helper = await FoliosCanceladosHelper.GetById(_proxyWebAPI, id);
            var data = helper.Result as FoliosCanceladosResponse ?? new FoliosCanceladosResponse();
            //var titular = model.GetTitular(id);            
            return Json(new
            {
                Error = false,
                Data =
                           new
                           {
                               data.Id,
                               data.Folio,
                               data.FechaCancelacion,
                               data.Motivo,
                               DatosUsuario = data.UsuarioAprobo,
                               data.TipoTramite,
                               data.DatosVehiculo,
                               data.PersonaRealizoTramite,
                               data.Fecha,
                               data.IdCatMotivoCancelacion,
                               data.OtroMotivo
                           }
            });
        }

        [HttpPost]
        public async Task<JsonResult> DetalleFolioImpresion(int id)
        {
            //var data = GetById(id);
            var helper = await FoliosCanceladosHelper.GetById(_proxyWebAPI, id);
            var data = helper.Result as FoliosCanceladosResponse ?? new FoliosCanceladosResponse();
            //var titular = model.GetTitular(id);            
            return Json(new
            {
                Error = !helper.IsSuccessFully,
                Html = !helper.IsSuccessFully ? "" : await this.RenderViewToStringAsync("~/Views/FoliosCancelados/_RegistroCancelado.cshtml", data)

            });
        }

        [HttpPost]
        public async Task<JsonResult> CancelarFolio(FolioCanceladosRequest request)
        {
            var result = new JsonResultDto();
            try
            {
                var usuarioActual = _userResolver.GetUser();

                if (usuarioActual != null)
                {
                    request.IdUser = usuarioActual.IdUser;
                    request.PersonaAprobo = usuarioActual.Nombre;
                }

                var helper = await FoliosCanceladosHelper.CancelarFolio(_proxyWebAPI, request);

                if (!helper.IsSuccessFully)
                {
                    result.Error = true;
                    result.ErrorDescription = helper.Message ?? _mensajeErrorCatch;
                    return Json(result);
                }
                result.Error = false;
                result.ErrorDescription = helper.Message ?? "El Folio fue cancelado correctamente";

            }
            catch (Exception e)
            {
                result.Error = true;

Smadot.Web/Views/FoliosCancelados/Index.cshtml
@using Smadot.Models.Dicts;
@inject Smadot.Utilities.GestionTokens.IUserResolver UserResolver
@{
    ViewData["Title"] = "Folios Cancelados";
    Layout = "~/Views/Shared/_LayoutSmadot.cshtml";
}
@section styles{
<link rel="stylesheet" href="~/lib/datatable/dist/css/dataTables.bootstrap4.min.css" />
<style>
    main[role="main"] h1, main[role="main"] h2, main[role="main"] h3, main[role="main"] h4, main[role="main"] h5, main[role="main"] h6 p {
        margin-bottom: 0px !important;
    }
</style>
}

@section breadcrumb{
<li class="breadcrumb-item text-muted">Administrar Formas Valoradas</li>
<li class="breadcrumb-item text-muted">
    <span class="bullet bg-gray-400 w-5px h-2px"></span>
</li>
@*<li class="breadcrumb-item text-muted">Folios Cancelados</li>
<li class="breadcrumb-item text-muted">
    <span class="bullet bg-gray-400 w-5px h-2px"></span>
</li>*@    
<li class="breadcrumb-item text-muted">Folios Cancelados</li>
<li class="breadcrumb-item text-muted">
    <span class="bullet bg-gray-400 w-5px h-2px"></span>
</li>
<li class="active">Consulta de Folios Cancelados</li>
}

@section toolbar{
    @if (UserResolver.HasPermission(MenuFoliosCancelados.Registrar))
    {
    <div class="btn-group dropup drop-up dropdown">
    <a class="btn btn-sm fw-bold btn-primary save" data-id="" asp-controller="FoliosCancelados" asp-action="Registro">Registrar Cancelación de Folio en Ventanilla</a>
    </div>
    }
}
<section>
        <div class="row">
            <!--begin::Col-->
            <div class="col-md-12">
                <!--begin::List widget 1-->
                <div class="card card-flush h-lg-100">
                    <!--begin::Body-->
                    <div class="card-body pt-5">
                        <div class="bottom-buffer">
                            <div class="datatable datatable-bordered datatable-head-custom">
                                <table class="table table-striped gx-7" id="kt_datatable"></table>
                            </div>
                        </div>
                    </div>
                    <!--end::Body-->
                </div>
                <!--end::LIst widget 1-->
            </div>
            <!--end::Col-->
        </div>
</section>
@section Scripts{
<script src="~/lib/datatable/dist/js/jquery.dataTables.min.js"></script>
<script src="~/lib/datatable/dist/js/dataTables.bootstrap4.min.js"></script>

<script src="~/js/FoliosCancelados/smadot.folioscancelados.index.js" asp-append-version="true"></script>
}

Smadot.Web/Views/FoliosCancelados/Registro.cshtml
@{
	ViewData["Title"] = "Registrar Cancelación de Folio en Ventanilla";
	Layout = "~/Views/Shared/_LayoutSmadot.cshtml";
}

@section styles{
	@*<link rel="stylesheet" href="~/lib/datatable/dist/css/dataTables.bootstrap4.min.css" />*@
	<link rel="stylesheet" href="~/lib/jquery-ui/dist/jquery-ui.min.css" type="text/css" />
	<style>
		.ui-autocomplete {
			position: absolute;
			cursor: default;
			z-index: 99999 !important;
		}
	</style>
}

	@section breadcrumb{
    <li class="breadcrumb-item text-muted">Administrar Formas Valoradas</li>
    <li class="breadcrumb-item text-muted">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
    <li class="breadcrumb-item text-muted">Folios Cancelados</li>
    <li class="breadcrumb-item text-muted">
        <span class="bullet bg-gray-400 w-5px h-2px"></span>
    </li>
	<li class="breadcrumb-item text-muted">
		<a class="text-muted" asp-controller="FoliosCancelados" asp-action="Index">Consulta de Folios Cancelados</a>	
	</li>
	<li class="breadcrumb-item text-muted">
		<span class="bullet bg-gray-400 w-5px h-2px"></span>
	</li>
    <li class="active">Registrar Cancelación de Folio en Ventanilla</li>
}

	@section toolbar{
}

<div class="card shadow-sm mb-5">
    <div class="card-body">
        <h4>Registrar Cancelación de Folio en Ventanilla</h4>
        <hr class="red">
        <div class="col-md-12">
            <div class="panel-body">
                <div class="row align-items-end mb-5 mt-5">
                    <div class="col-md-4">
                        <div class="form-check form-check-custom form-check-success form-check-solid">
							<input class="form-check-input" type="checkbox" value="" checked id="FolioExists" name="FolioExists" />
							<label class="form-check-label" for="FolioExists">Folio registrado en el sistema</label>
                        </div>
                    </div>
                    <div class="form-group input-group-sm col-md-6" id="autocompleteDiv">
                        <input type="text" id="ConsultaFolio" name="ConsultaFolio" class="form-control" placeholder="Búsqueda de Folio">

					</div>
					<div class="col-md-6 row" id="nuevoFolioDiv" style="display:none">
						<div class="form-group input-group-sm col-md-6">
							<label class="control-label">Folio</label>
							<input id="FolioNuevo" name="FolioNuevo" class="form-control" type="number" />
						</div>
						<div class="form-group input-group-sm col-md-6">
							<label class="control-label">Tipo de Certificado</label>
							<select id="IdCatTipoCertificado" name="IdCatTipoCertificado" class="form-control" data-control="select2" asp-items="(List<SelectListItem>)ViewBag.Certificados">
								<option value="0">Seleccione</option>
							</select>
						</div>
					</div>
                </div>

            </div>
        </div>
    </div>
    @*<div class="card-footer d-flex justify-content-end py-6 px-9">
    <input class="btn btn-primary btn-sm pull-right" type="button" id="reasignarExpediente_btnAgregar" value="Agregar" />
    </div>*@
</div>

	<div class="card shadow-sm mb-5" id="DetalleFolio" style="display:none">
		<div class="card-body">
			<div class="col-md-12">
				<div class="panel-body">
					<div class="row align-items-end mb-5 mt-5 detalleFolioRow" style="display:none">
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Folio</label>
							<input type="text" id="FolioId" name="FolioId" class="form-control" placeholder="Folio" disabled>
							<input type="hidden" id="IdF" />
						</div>
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Tipo de Trámite</label>
							<input type="text" id="Tipo" name="Tipo" class="form-control" disabled>
						</div>
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Fecha</label>
							<input type="text" id="Fecha" name="Fecha" class="form-control" disabled>
						</div>
					</div>

				<div class="row align-items-end mb-5 mt-5 detalleFolioRow" style="display:none">
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Datos de Usuario</label>
							<input type="text" id="Usuario" name="Usuario" class="form-control" disabled>
						</div>
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Datos de Vehículo</label>
							<input type="text" id="Vehiculo" name="Vehiculo" class="form-control" disabled>
						</div>
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Persona que realizó el trámite</label>
							<input type="text" id="Persona" name="Persona" class="form-control" disabled>
						</div>
					</div>

					<div class="row align-items-end mb-5 mt-5">
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Fecha de Cancelación</label>
							<input type="text" id="FechaC" name="FechaC" class="form-control" >
						</div>
						<div class="form-group input-group-sm col-md-4">
							<label class="control-label">Motivo de Cancelación</label>
							@*<input type="text" id="Motivo" name="Motivo" class="form-control" >*@
							<select id="Motivo" name="Motivo" class="form-control">
							<option value="0">Seleccione</option>
							<option value="1">Mala Impresión</option>
								<option value="2">Folio Defectuoso</option>
								<option value="3">Otro</option>
							</select>
						</div>
						<div class="form-group input-group-sm col-md-4" style="display:none" id="InputOtro">
							<label class="control-label">Otro</label>
							<input type="text" id="Otro" name="Otro" class="form-control" >
						</div>
					</div>

				</div>
			</div>
		</div>
		<div class="card-footer d-flex justify-content-end py-6 px-9">
			<a class="btn btn-secondary btn-sm pull-right" id="btnCancelarFolio" asp-action="Index" asp-controller="FoliosCancelados">Cancelar</a> &nbsp;&nbsp;&nbsp;
			<button class="btn btn-primary btn-sm pull-right" type="button" id="btnGuardarFolio">Guardar</button>
		</div>

	</div>
	

	@section Scripts{

	@*<script src="~/lib/jquery/dist/jquery.min.js"></script>	*@
	<script src="~/lib/jquery-ui/dist/jquery-ui.min.js"></script>
	<script src="~/lib/daterangepicker/js/daterangepicker.js"></script>
	<script asp-append-version="true" src="~/js/FoliosCancelados/smadot.folioscancelados.registro.js"></script>
}

Smadot.Web/Views/FoliosCancelados/_RegistroCancelado.cshtml
@model Smadot.Models.Entities.FoliosCancelados.Response.FoliosCanceladosResponseData.FoliosCanceladosResponse
<form class="" id="form_registro">
    <div class="col-md-12">
        <div class="panel-body">
            <div class="row align-items-end mb-5 mt-5">
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Folio</label>
                    <input type="text" asp-for="Folio" class="form-control" placeholder="Folio" readonly>
                    <input type="hidden" asp-for="Id" class="form-control" placeholder="Folio" readonly>
                </div>
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Tipo de Trámite</label>
                    <input type="text" asp-for="TipoTramite" class="form-control" disabled>
                </div>
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Fecha</label>
                    <input type="text" asp-for="Fecha" class="form-control" disabled>
                </div>
            </div>

            <div class="row align-items-end mb-5 mt-5">
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Datos de Usuario</label>
                    <input type="text" asp-for="UsuarioAprobo" class="form-control" disabled>
                </div>
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Datos de Vehículo</label>
                    <input type="text" asp-for="DatosVehiculo" class="form-control" disabled>
                </div>
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Persona que realizó el trámite</label>
                    <input type="text" asp-for="PersonaRealizoTramite" class="form-control" disabled>
                </div>
            </div>

            <div class="row align-items-end mb-5 mt-5">
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Fecha de Cancelación</label>
                    <input type="text" asp-for="FechaCancelacion" class="form-control">
                </div>
                <div class="form-group input-group-sm col-md-4">
                    <label class="control-label">Motivo de Cancelación</label>
                    @*<input type="text" id="Motivo" name="Motivo" class="form-control" >*@
                    <select asp-for="IdCatMotivoCancelacion" class="form-control">
                        <option value="">Seleccione</option>
                        <option value="1">Mala Impresión</option>
                        <option value="2">Folio Defectuoso</option>
                        <option value="3">Otro</option>
                    </select>
                </div>
                <div class="form-group input-group-sm col-md-4" style="display:none" id="InputOtro">
                    <label class="control-label">Otro</label>
                    <input type="text" asp-for="OtroMotivo" class="form-control">
                </div>
            </div>

        </div>
    </div>
</form>